DISABLE_AUTO_UPDATE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_COMPFIX="true"
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="20"
ZSH_AUTOSUGGEST_USE_ASYNC=1

export PATH=$HOMEBREW_PREFIX/opt/python@3.13/libexec/bin:$PATH

alias json="pbpaste | jq -C \".\""
alias jsonout="pbpaste | jq \".\""
alias cj="jq -C \".\""

alias utc='zdump UTC'
alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
alias mux='tmuxinator'

faws(){
  if [ "$1" = "prod" ]; then
    region="us-east-1"
    echo 'Logging into ' $region
  else
    region="us-west-2"
    echo 'Logging into ' $region
  fi
  : > ~/.aws/credentials; saml2aws login --session-duration=43200 --region $region --skip-prompt --skip-verify;grep -ilr 'Google-PlatformEng' ~/.aws/credentials | sed -i '' 's/region.*/region='$region'/' ~/.aws/credentials;export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain zignal --domain-owner 121286554335 --query authorizationToken --output text`
}

export AWS_PROFILE="Google-PlatformEng"
export CLAUDE_CODE_USE_BEDROCK=1
export AWS_DEFAULT_REGION=us-west-2
export ANTHROPIC_MODEL='arn:aws:bedrock:us-west-2:121286554335:application-inference-profile/3i4ptd2b4d0t'
export ANTHROPIC_DEFAULT_HAIKU_MODEL='arn:aws:bedrock:us-west-2:121286554335:application-inference-profile/0ls7cm40jo4m'
export CLAUDE_CODE_MAX_OUTPUT_TOKENS=4096
export MAX_THINKING_TOKENS=1024

export ANTIDOTE_HOME=~/.cache/antidote
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
source <(antidote init)

antidote bundle getantidote/use-omz
antidote bundle ohmyzsh/ohmyzsh path:lib
antidote bundle ohmyzsh/ohmyzsh path:plugins/git
antidote bundle ohmyzsh/ohmyzsh path:plugins/1password
antidote bundle ohmyzsh/ohmyzsh path:plugins/autojump
antidote bundle ohmyzsh/ohmyzsh path:plugins/thefuck
antidote bundle MichaelAquilina/zsh-autoswitch-virtualenv


# Syntax highlighting bundle.
antidote bundle zsh-users/zsh-syntax-highlighting

# Fish-like auto suggestions
antidote bundle zsh-users/zsh-autosuggestions

# Extra zsh completions
antidote bundle zsh-users/zsh-completions

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export EDITOR=$HOMEBREW_PREFIX/bin/vim

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

eval $(thefuck --alias)

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/jakeschwartz/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi
# End of lines added by compinstall

export NVM_DIR="$HOME/.nvm"
[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"  # This loads nvm
[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export STARSHIP_CONFIG=~/Dev/dotfiles/starship.toml
eval "$(starship init zsh)"
