# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $(brew --prefix)/share/antigen/antigen.zsh
antigen use oh-my-zsh

antigen bundle autojump
antigen bundle brew
antigen bundle common-aliases
antigen bundle copyfile
antigen bundle git
antigen bundle osx
antigen bundle sbt
antigen bundle thefuck
antigen bundle tmux
antigen bundle tmuxinator

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Fish-like auto suggestions
antigen bundle zsh-users/zsh-autosuggestions

# Extra zsh completions
antigen bundle zsh-users/zsh-completions

# Virtual environment niceities
antigen bundle MichaelAquilina/zsh-autoswitch-virtualenv

# Load the theme
antigen theme romkatv/powerlevel10k

antigen apply

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$PATH:$HOME/Dev/flutter/bin"

alias json="pbpaste | fx ."
alias utc='zdump UTC'
alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
alias mux='tmuxinator'
alias push='git push origin HEAD'
alias pr='git push origin HEAD && open $(gh pr create -f)'
alias faws=": > ~/.aws/credentials;wait 8; saml2aws login --region us-east-1;grep -ilr 'Google-PlatformEng' ~/.aws/credentials | xargs -I@ sed -i '' 's/Google-PlatformEng/default/g' @; sed -i '' 's/region.*/region=us-east-1/' ~/.aws/credentials"


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

export EDITOR=/usr/bin/vim

