mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Xcode", id: 497799835
tap "caskroom/cask-versions"
tap "elastic/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sinclairtarget/wst"
brew "autojump"
brew "python"
brew "antigen"
brew "awscli"
brew "bat"
brew "blueutil"
brew "fx"
brew "fzf"
brew "git"
brew "giter8"
brew "gmp"
brew "httpie"
brew "hugo"
brew "mackup"
brew "mas"
brew "redis"
brew "rename"
brew "sbt"
brew "shpotify"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "unrar"
brew "vim"
brew "youtube-dl"
brew "elastic/tap/elasticsearch-full"
cask "cleanmymac"
cask "dropbox"
cask "font-fira-code"
cask "google-backup-and-sync"
cask "google-chrome"
cask "intellij-idea"
cask "iterm2"
cask "java8"
cask "megasync"
cask "postman"
cask "qlvideo"
cask "quicklook-json"
cask "remembear"
cask "slack"
cask "spotify"
cask "tunnelblick"
cask "visualvm"
cask "vlc"

