tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ammonite-repl"
brew "autojump"
brew "bat"
brew "fx"
brew "git"
brew "giter8"
brew "hugo"
brew "mas"
brew "sbt"
brew "thefuck"
brew "tldr"
brew "tree"
brew "unrar"
brew "vim"
cask "airflow" 
cask "boom-3d"
cask "cleanmymac"
cask "docker"
cask "dropbox"
cask "font-fira-code"
cask "google-backup-and-sync"
cask "google-chrome"
cask "intellij-idea"
cask "iterm2"
cask "java8"
cask "megasync"
cask "qlmarkdown"
cask "qlvideo"
cask "quicklook-json"
cask "remembear"
cask "slack"
cask "spotify"
cask "tunnelblick"
cask "vlc"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Xcode", id: 497799835
